name: Python Image Grid Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: upgrade pip and install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Build Project
        run: |
          python setup.py install
      - name: Run Tests
        run: |
          pytest